spring.application.name=minimarket

# Configuracion de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuracion de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Permite que Hibernate cree las tablas ANTES de ejecutar data.sql
spring.jpa.defer-datasource-initialization=true

# JWT
security.jwt.expiration-seconds=3600
security.jwt.secret=minimarket-backend2-jwt-secret-key-super-segura-2026-demo

# Logs del sistema
# Guarda los eventos de la aplicacion en un archivo para trazabilidad.
logging.file.name=logs/minimarket-security.log